# Generated by Django 3.0.8 on 2020-07-25 20:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='create_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 7, 26, 2, 16, 25, 867940)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(default='active', max_length=15),
        ),
    ]
