# Generated by Django 3.0.8 on 2020-07-22 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=130)),
                ('image', models.CharField(max_length=1000)),
                ('starting_bid', models.FloatField()),
                ('current_bid', models.FloatField()),
                ('bid_increment', models.FloatField()),
                ('condition', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='UserBid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_bid', models.FloatField()),
                ('current_bid', models.FloatField()),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.Listing')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='bids',
            field=models.ManyToManyField(blank=True, related_name='bidder', to='auctions.UserBid'),
        ),
        migrations.AddField(
            model_name='user',
            name='listing',
            field=models.ManyToManyField(blank=True, related_name='creater', to='auctions.Listing'),
        ),
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='watchers', to='auctions.Listing'),
        ),
    ]
