# Generated by Django 3.0.8 on 2020-07-26 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20200726_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bought_items',
            field=models.ManyToManyField(blank=True, related_name='buyer', to='auctions.Listing'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='create_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 7, 26, 18, 24, 22, 223217)),
        ),
    ]
