# Generated by Django 3.0.8 on 2020-07-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200722_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='commenter', to='auctions.UserComment'),
        ),
    ]
