# Generated by Django 3.0.8 on 2020-07-27 14:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200726_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='comments',
        ),
        migrations.AddField(
            model_name='usercomment',
            name='commenter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usercomment',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=datetime.datetime.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='create_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 7, 27, 20, 15, 36, 856825)),
        ),
        migrations.RemoveField(
            model_name='usercomment',
            name='listing',
        ),
        migrations.AddField(
            model_name='usercomment',
            name='listing',
            field=models.ManyToManyField(related_name='comments', to='auctions.Listing'),
        ),
    ]
