# Generated by Django 3.0.8 on 2020-07-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200722_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomment',
            name='comment',
            field=models.TextField(),
        ),
    ]
