# Generated by Django 3.0.8 on 2020-07-22 14:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20200722_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='create_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
