# Generated by Django 3.0.8 on 2020-07-22 19:38

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_remove_listing_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=datetime.datetime(2020, 7, 23, 1, 7, 44, 672330)),
            preserve_default=False,
        ),
    ]
