# Generated by Django 3.0.8 on 2020-07-23 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_listing_create_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='bid_increment',
        ),
        migrations.AlterField(
            model_name='listing',
            name='create_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 7, 23, 15, 38, 19, 769449)),
        ),
    ]
