# Generated by Django 3.0.8 on 2020-07-23 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20200723_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(default='No Category Listed', max_length=45),
        ),
        migrations.AlterField(
            model_name='listing',
            name='create_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 7, 23, 16, 24, 3, 660579)),
        ),
    ]
