# Generated by Django 3.0.8 on 2020-07-23 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20200723_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='create_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 7, 23, 17, 59, 10, 666710)),
        ),
    ]
