# Generated by Django 3.0.8 on 2020-07-23 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auto_20200723_1759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbid',
            old_name='max_bid',
            new_name='bid',
        ),
        migrations.AlterField(
            model_name='listing',
            name='create_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 7, 23, 22, 18, 42, 375031)),
        ),
    ]
