# Generated by Django 3.0.8 on 2020-07-23 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_auto_20200723_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='create_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 7, 24, 0, 45, 6, 464840)),
        ),
    ]
