# Generated by Django 3.0.8 on 2020-07-24 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_auto_20200724_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(default='No category provided', max_length=45),
        ),
        migrations.AlterField(
            model_name='listing',
            name='create_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 7, 24, 19, 23, 33, 967741)),
        ),
    ]
